name: data update

on:
  push:
  schedule:
    - cron: '5 * * * 0' #UTC

jobs:
  data_update_job:
    runs-on: ubuntu-latest
    name: data update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: pip
        run: |
          pip install pandas requests
      - name: git clone data_setup
        run: |
          git clone --depth 1 https://github.com/Code-for-Fukuoka/data_setup data_setup
      - name: run script
        run: |
          sed -i -E "s|\[本ツール（data_setup）が置かれているディレクトリ\]|$GITHUB_WORKSPACE|" ./data_setup/script/run_gen.sh
          sed -i -E "s|\[本ツール（data_setup）が置かれているディレクトリ\]|$GITHUB_WORKSPACE|" ./data_setup/config.ini
          cat ./data_setup/script/run_gen.sh
          ./data_setup/script/run_gen.sh
      - name: Copy data files
        run: |
          cp -f ./data_setup/gen_data/data.json ./data/data.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
